[package]
name = "x-link-types"
version = "0.1.0"
edition = "2021"

[dependencies]

# Json
serde = { workspace = true}
serde_json = { workspace = true}

# Solana stuff
solana-sdk = { workspace = true}
